-- ─────────────────────────────────────────────────────────────────────────────
-- Make indicators a single global vocabulary (drop per-project scoping).
--
-- Previously custom indicators (is_standard = false) were pinned to one project
-- via `indicators.project_id`, so a custom indicator created in one project was
-- invisible to every other. This drops that scoping: indicators are now a shared
-- library distinguished only by `is_standard`. The reference direction is one-way
-- — reports/prodocs point at an indicator through `indicator_data`; the indicator
-- no longer points back at a project. Existing custom indicators keep their rows
-- and all their indicator_data links, and simply become searchable everywhere.
--
-- Non-destructive: no indicator rows or indicator_data links are removed. Only the
-- project_id column (and its CHECK constraint + index) are dropped.
--
-- Idempotent: safe to run more than once. Run once against each live database.
-- ─────────────────────────────────────────────────────────────────────────────

SET search_path TO reporting_platform;

-- Drop the (is_standard ⇔ project_id null) CHECK. Its name is autogenerated, so
-- find and drop whichever check constraint references project_id.
DO $$
DECLARE
  con_name TEXT;
BEGIN
  SELECT c.conname INTO con_name
    FROM pg_constraint c
   WHERE c.conrelid = 'reporting_platform.indicators'::regclass
     AND c.contype  = 'c'
     AND pg_get_constraintdef(c.oid) ILIKE '%project_id%';
  IF con_name IS NOT NULL THEN
    EXECUTE format('ALTER TABLE indicators DROP CONSTRAINT %I', con_name);
  END IF;
END $$;

DROP INDEX IF EXISTS indicators_project_idx;

ALTER TABLE indicators DROP COLUMN IF EXISTS project_id;
